### ISSUE TITLE
Unable to extract edsk file

### ISSUE THREAD

**Issue by neuromancer** [damieng/DiskImageManager#5]
This [edsk file](https://spectrumcomputing.co.uk/pub/sinclair/games/c/CastleMaster(ErbeSoftwareS.A.).dsk.zip) fails to be parsed correctly in the latest release. It seems it contains the following files:

* CMCODE
* CMCON
* CML
* CMLSC
* FAD.SCR

But it only detects two file, and the names seems corrupted.

**Comment by damieng** [comment]
Hi, sorry for the late reply, not sure why I wasn't getting notifications for my repo.

This issue was caused by the Amstrad CPC and DATA format detection using the sector ID of the first physical sector in the disk image. The image you provided was skewed in that the first logical sector was at the end.

I've corrected the bug in the 2.8.1 release and it now uses the logical sector - which is what it was always supposed to do.

**Comment by neuromancer** [comment]
It works, thanks a lot!
